[package]
name = "coop_content_types"
version = "0.1.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "coop_content_types"
crate-type = ["cdylib", "rlib"]

[dependencies]
hdi = "0.4.0-beta-dev.1"
hdk = "0.3.0-beta-dev.2"
rmpv = { version = "1.0.0", features = ["with-serde"] }
serde = "1"
thiserror = "1"
whi_hdk_extensions = "0.1"
# whi_hdk_extensions = { path = "../../whi_hdk_extensions" }
