[package]
name = "hc_hdk_extensions"
version = "0.1.0"
authors = ["Matthew Brisebois <matthew.brisebois@holo.host>"]
edition = "2018"

[lib]
name = "hdk_extensions"

[dependencies]
hc_hdi_extensions = { path = "../hdi_extensions" }
hdk = "0.3.0-beta-dev.2"
serde = "1"
thiserror = "1"
